### ISSUE TITLE
ValueError: image at 000000000009.jpg doesn't have metadata

### ISSUE THREAD

**Issue by mochiduki-01** [Georgefwt/AquaLoRA#8]
Hello, sorry to bother you again.

In `rob_enhance_finetune.py`, I encountered the following error:

```
Traceback (most recent call last):
  File "/home/halt/anaconda3/envs/aqualora_env/lib/python3.10/site-packages/datasets/builder.py", line 1676, in _prepare_split_single
    for key, record in generator:
  File "/home/halt/anaconda3/envs/aqualora_env/lib/python3.10/site-packages/datasets/packaged_modules/folder_based_builder/folder_based_builder.py", line 311, in _generate_examples
    raise ValueError(
ValueError: image at 000000000009.jpg doesn't have metadata in /home/halt/AquaLoRA/train/../COCO2017test/train/metadata.jsonl.
```

The dataset being used is `coco2017/train2017`, with the directory name modified. As specified, the provided `metadata.jsonl` file is placed in the same directory as the images.
Additionally, I executed the following command:
```
export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export TRAIN_DIR="../COCO2017test/train"

accelerate launch --mixed_precision="fp16" rob_enhance_finetune.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --train_data_dir=$TRAIN_DIR --caption_column="text" \
  --resolution=512 \
  --dataloader_num_workers=16 \
  --train_batch_size=16 \
  --num_train_epochs=10 --checkpointing_steps=200 \
  --learning_rate=5e-06 --lr_scheduler="cosine_with_restarts" --lr_warmup_steps=0 --lr_end=0.1 \
  --seed=65535 \
  --output_dir="../output3" \
  --start_from_pretrain="pretained_latentwm.pth" \
  --resume_from_lora="../output2" \
  --validation_prompt="A portrait of a young white woman, masterpiece" \
  --validation_epochs=1 \
  --rank=320 \
  --msg_bits=48
```
The overall directory structure is as follows:
```
COCO2017test
└── train
    ├── 000000000071.jpg
    ├── other jpgs...
    └── metadata.jsonl
output1
output2
train
├── latent_wm_pretrain.py
├── ppft_train.py
├── rob_enhance_finetune.py
└── pretained_latentwm.pth
```
Finally, below are the results of `pip list` for my virtual environment "aqualora_env" on Anaconda3.
```
Package                   Version
------------------------- -----------
absl-py                   2.1.0
accelerate                0.28.0
aiofiles                  24.1.0
aiohappyeyeballs          2.3.4
aiohttp                   3.10.0
aiosignal                 1.3.1
altair                    5.3.0
annotated-types           0.7.0
antlr4-python3-runtime    4.9.3
anyio                     4.4.0
async-timeout             4.0.3
attrs                     23.2.0
bitsandbytes              0.43.1
cachetools                5.4.0
certifi                   2024.7.4
charset-normalizer        3.3.2
click                     8.1.7
clip                      1.0
cmake                     3.30.1
ConfigArgParse            1.7
contourpy                 1.2.1
cycler                    0.12.1
datasets                  2.14.5
diffusers                 0.24.0
dill                      0.3.7
DISTS-pytorch             0.1
dreamsim                  0.1.3
einops                    0.7.0
exceptiongroup            1.2.2
fastapi                   0.112.0
ffmpy                     0.4.0
filelock                  3.15.4
fonttools                 4.53.1
frozenlist                1.4.1
fsspec                    2023.6.0
ftfy                      6.2.0
google-auth               2.32.0
google-auth-oauthlib      1.0.0
gradio                    3.20.1
grpcio                    1.65.4
h11                       0.14.0
httpcore                  1.0.5
httpx                     0.27.0
huggingface-hub           0.21.4
idna                      3.7
importlib_metadata        8.2.0
Jinja2                    3.1.4
jsonlines                 4.0.0
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
kornia                    0.6.12
lightning-utilities       0.11.6
linkify-it-py             2.0.3
lit                       18.1.8
lpips                     0.1.4
Markdown                  3.6
markdown-it-py            2.2.0
MarkupSafe                2.1.5
matplotlib                3.9.1
mdit-py-plugins           0.3.3
mdurl                     0.1.2
mpmath                    1.3.0
multidict                 6.0.5
multiprocess              0.70.15
networkx                  3.3
numpy                     1.24.3
nvidia-cublas-cu11        11.10.3.66
nvidia-cuda-cupti-cu11    11.7.101
nvidia-cuda-nvrtc-cu11    11.7.99
nvidia-cuda-runtime-cu11  11.7.99
nvidia-cudnn-cu11         8.5.0.96
nvidia-cufft-cu11         10.9.0.58
nvidia-curand-cu11        10.2.10.91
nvidia-cusolver-cu11      11.4.0.1
nvidia-cusparse-cu11      11.7.4.91
nvidia-nccl-cu11          2.14.3
nvidia-nvtx-cu11          11.7.91
oauthlib                  3.2.2
omegaconf                 2.3.0
open-clip-torch           2.24.0
opencv-python             4.7.0.72
orjson                    3.10.6
packaging                 24.1
pandas                    2.2.2
peft                      0.1.0
pillow                    10.4.0
pip                       24.0
protobuf                  5.27.3
psutil                    6.0.0
pyarrow                   17.0.0
pyasn1                    0.6.0
pyasn1_modules            0.4.0
pycryptodome              3.20.0
pydantic                  2.8.2
pydantic_core             2.20.1
pydub                     0.25.1
pyparsing                 3.1.2
python-dateutil           2.9.0.post0
python-multipart          0.0.9
pytorch-lightning         2.2.5
pytz                      2024.1
PyYAML                    6.0.1
referencing               0.35.1
regex                     2024.7.24
requests                  2.32.3
requests-oauthlib         2.0.0
rpds-py                   0.19.1
rsa                       4.9
safetensors               0.4.2
scipy                     1.11.1
sentencepiece             0.2.0
setuptools                69.5.1
six                       1.16.0
sniffio                   1.3.1
starlette                 0.37.2
sympy                     1.13.1
tensorboard               2.14.0
tensorboard-data-server   0.7.2
timm                      0.9.5
tokenizers                0.13.3
toolz                     0.12.1
torch                     2.0.1
torch-fidelity            0.3.0
torchaudio                2.0.2
torchmetrics              0.11.4
torchsummary              1.5.1
torchvision               0.15.2
tqdm                      4.65.0
transformers              4.26.1
triton                    2.0.0
typing_extensions         4.12.2
tzdata                    2024.1
uc-micro-py               1.0.3
urllib3                   2.2.2
uvicorn                   0.30.5
wcwidth                   0.2.13
websockets                12.0
Werkzeug                  3.0.3
wheel                     0.43.0
xxhash                    3.4.1
yarl                      1.9.4
zipp                      3.19.2
```

Thank you.

**Comment by Georgefwt** [comment]
sorry for the super late reply!
I personally never encountered such problems, it seems like the problem with diffusers? https://github.com/huggingface/diffusers/issues/3674
Hope this might help.

**Comment by mochiduki-01** [comment]
Thank you for your response.
And I apologize for the delayed reply.

I tried the solution from the URL you provided, but it didn't work. After investigating, I suspect that the issue might be related to the compatibility with the COCO2017 dataset provided by Kaggle.

In fact, captions for the downloaded images, such as `000000000009.jpg` and `000000000025.jpg`, are not recorded in `metadata.jsonl`.
Would it be necessary to remove all images that are not listed in `metadata.jsonl`?

However, what seems curious is that PPFT appears to complete execution successfully until the end.

I appreciate your help.

**Comment by Georgefwt** [comment]
I'd recommend ensuring your image dataset and metadata are properly aligned. You can filter out images not listed in `metadata.jsonl`, or update the metadata file to include all images.

Additionally, you don't necessarily need to follow the `metadata.jsonl` I provided - you can also use your own data. You could also sample images using these captions, and then train with the sampled images.

**Comment by mochiduki-01** [comment]
If I want to reproduce the values of your paper, should I remove the images to match the current metadata?

**Comment by Georgefwt** [comment]
Yes, I suggest you remove the images to match the current metadata.

**Comment by mochiduki-01** [comment]
Thank you very much. I will try that.

**Comment by mochiduki-01** [comment]
Hello.
After organizing the data set, I was able to obtain values close to those in the paper.

Thank you very much for your advice.
I will close the issue.
